---

  - apt: update_cache=yes

  - name: ensures that the required packages are present
    apt: name={{ item }} state=latest
    with_items:
      - build-essential
      - python-pip
      - libmysqlclient-dev
      - python-dev
      - mysql-server

  - name: ensures that the required python packages are installed
    pip: name=MySQL-python
