---

  - name: Ensure the file that allows external connection is present
    copy: src=allow_external.cnf dest=/etc/mysql/conf.d/allow_external.cnf

  - name: restarts mysql service
    service: name=mysql state=restarted

  - name: ensures that the {{ item.name }} exists
    mysql_db: name={{ item.name }} state=present
    with_items: "{{ mysql }}"

  - name: remote user
    shell: mysql -u root -e "SELECT user FROM mysql.user"
    register: check_user
    changed_when:  "'{{remote_user}}' not in check_user.stdout"
    failed_when: check_user.rc != 0
    sudo: no

  - name: create remote user
    shell: mysql -u root -e "GRANT ALL PRIVILEGES ON {{item.name}}.* TO '{{remote_user}}'@'%' IDENTIFIED BY '{{remote_user_password}}';"
    register: remote_user
    failed_when: remote_user.rc != 0
    when: check_user|changed
    sudo: no
    with_items: "{{ mysql }}"
