home_directory: "/home/vagrant"
remote_user: "dashboard"
remote_user_password: "password"
mysql:
  - env: test
    name: 'sandbox_test'
    file: 'schema.sql'
  - env: prod
    name: 'sandbox'
    file: 'mysqldump.sql'
